apiVersion: v1
kind: Pod
metadata:
  name: poller
spec:
  containers:
    - name: poller
      image: thundernetes-maintenance-poller:17eb975
      env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
  restartPolicy: Never
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-patcher
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-patcher-poller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-patcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: default